

// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
 
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Dungecto")]
[assembly: AssemblyProduct("Dungecto")]
[assembly: AssemblyCompany("AliveDiv")]
[assembly: AssemblyCopyright("Copyright © 2015 AliveDiv, All rights reserved.")]

// MajorVersion = Public releases
// MinorVersion = Functions added/removed/changed
// BuildNumber = Bug fixes & other things
// RevisionNumber = total days of development
[assembly: AssemblyVersion("1.0.1.101")]
[assembly: AssemblyFileVersion("1.0.1.101")]
 
