//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dungecto.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dungecto.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungecto.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main menu.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MainMenuNew {
            get {
                return ResourceManager.GetString("MainMenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MainMenuOpen {
            get {
                return ResourceManager.GetString("MainMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string MainMenuSave {
            get {
                return ResourceManager.GetString("MainMenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as image.
        /// </summary>
        public static string MainMenuSaveAsImage {
            get {
                return ResourceManager.GetString("MainMenuSaveAsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string MapBackground {
            get {
                return ResourceManager.GetString("MapBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string MapColumns {
            get {
                return ResourceManager.GetString("MapColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map properties.
        /// </summary>
        public static string MapProperties {
            get {
                return ResourceManager.GetString("MapProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows:.
        /// </summary>
        public static string MapRows {
            get {
                return ResourceManager.GetString("MapRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector height (in px):.
        /// </summary>
        public static string SectorHeight {
            get {
                return ResourceManager.GetString("SectorHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector width (in px):.
        /// </summary>
        public static string SectorWidth {
            get {
                return ResourceManager.GetString("SectorWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string TileColor {
            get {
                return ResourceManager.GetString("TileColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string TileHeight {
            get {
                return ResourceManager.GetString("TileHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position X.
        /// </summary>
        public static string TilePositionX {
            get {
                return ResourceManager.GetString("TilePositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Y.
        /// </summary>
        public static string TilePositionY {
            get {
                return ResourceManager.GetString("TilePositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Z.
        /// </summary>
        public static string TilePositionZ {
            get {
                return ResourceManager.GetString("TilePositionZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile properties.
        /// </summary>
        public static string TileProperties {
            get {
                return ResourceManager.GetString("TileProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Remove.
        /// </summary>
        public static string TileRemove {
            get {
                return ResourceManager.GetString("TileRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string TileWidth {
            get {
                return ResourceManager.GetString("TileWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        public static string Toolbox {
            get {
                return ResourceManager.GetString("Toolbox", resourceCulture);
            }
        }
    }
}
